from setuptools import setup
setup(
    name='PyCurrency-Converter',
    packages=['PyCurrency_Converter'],
    version='1.0',
    license='GNU General Public License v3 (GPLv3)',
    requires='BeautifulSoup',
    description='A python library to convert currency using Google Finance.',
    long_description='Visit http://siddharthsaxena.weebly.com/pycurrency-converter.html for more details.',
    author='Siddharth Saxena',
    author_email='siddharth.saxena25@gmail.com',
    url='https://github.com/SiddharthSaxena/PyCurrency-Converter',
    download_url='https://github.com/SiddharthSaxena/PyCurrency-Converter',
    keywords=['currency converter google'],
    classifiers=['Development Status :: 5 - Production/Stable',
                 'Topic :: Software Development :: Libraries',
                 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.6',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.2',
                 'Programming Language :: Python :: 3.3',
                 'Programming Language :: Python :: 3.4',
                 'Programming Language :: Python :: 3.5']
)
